"""Add relacionamento fornecedor-produto

Revision ID: 02fc4b55b9c1
Revises: db4954e35327
Create Date: 2025-11-21 10:38:43.038346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '02fc4b55b9c1'
down_revision: Union[str, Sequence[str], None] = 'db4954e35327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
