"""inicio4

Revision ID: 5b8dc5ea9b69
Revises: f4ea897008ed
Create Date: 2025-11-18 16:11:56.546986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5b8dc5ea9b69'
down_revision: Union[str, Sequence[str], None] = 'f4ea897008ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor',
    sa.Column('idForn', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contato', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('idForn')
    )
    op.create_table('produto',
    sa.Column('idProd', sa.Integer(), nullable=False),
    sa.Column('mercadoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('idProd')
    )
    op.create_table('produtofornecedor',
    sa.Column('produto', sa.Integer(), nullable=False),
    sa.Column('fornecedor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor'], ['fornecedor.idForn'], ),
    sa.ForeignKeyConstraint(['produto'], ['produto.idProd'], ),
    sa.PrimaryKeyConstraint('produto', 'fornecedor')
    )
    op.create_table('transacao',
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_transacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.idForn'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.idProd'], ),
    sa.PrimaryKeyConstraint('produto_id', 'fornecedor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacao')
    op.drop_table('produtofornecedor')
    op.drop_table('produto')
    op.drop_table('fornecedor')
    # ### end Alembic commands ###
