"""tirando tpo de transacao

Revision ID: 8c46dba2f60c
Revises: a4752ceaeae5
Create Date: 2025-11-22 17:08:16.991338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8c46dba2f60c'
down_revision: Union[str, Sequence[str], None] = 'a4752ceaeae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor',
    sa.Column('idForn', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contato', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('idForn')
    )
    op.create_table('produto',
    sa.Column('idProd', sa.Integer(), nullable=False),
    sa.Column('mercadoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('idProd')
    )
    op.create_table('transacao',
    sa.Column('transacao_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_transacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('transacao_id')
    )
    op.create_table('produtotransacaofornecedor',
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('transacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.idForn'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.idProd'], ),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacao.transacao_id'], ),
    sa.PrimaryKeyConstraint('produto_id', 'fornecedor_id', 'transacao_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtotransacaofornecedor')
    op.drop_table('transacao')
    op.drop_table('produto')
    op.drop_table('fornecedor')
    # ### end Alembic commands ###
