"""mudanca no banco dnovo

Revision ID: eca030b29dbe
Revises: 783a76812c3b
Create Date: 2025-11-20 11:29:14.387307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eca030b29dbe'
down_revision: Union[str, Sequence[str], None] = '783a76812c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtotransacaofornecedor',
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('transacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.idForn'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.idProd'], ),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacao.transacao_id'], ),
    sa.PrimaryKeyConstraint('produto_id', 'fornecedor_id', 'transacao_id')
    )
    op.drop_table('produtofornecedor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtofornecedor',
    sa.Column('produto', sa.INTEGER(), nullable=False),
    sa.Column('fornecedor', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor'], ['fornecedor.idForn'], ),
    sa.ForeignKeyConstraint(['produto'], ['produto.idProd'], ),
    sa.PrimaryKeyConstraint('produto', 'fornecedor')
    )
    op.drop_table('produtotransacaofornecedor')
    # ### end Alembic commands ###
