"""create fornecedor table

Revision ID: f1a2b3c4d5e6
Revises: eca030b29dbe
Create Date: 2025-11-28 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f1a2b3c4d5e6'
down_revision: Union[str, Sequence[str], None] = 'eca030b29dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor',
    sa.Column('idForn', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('contato', sa.String(), nullable=False),
    sa.Column('endereco', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idForn')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fornecedor')
    # ### end Alembic commands ###
