"""adicionar quantidade para tabela produto_transacao_fornecedor

Revision ID: 044784c3d055
Revises: d7c149b6b5ae
Create Date: 2025-11-30 12:35:37.377125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044784c3d055'
down_revision: Union[str, Sequence[str], None] = 'd7c149b6b5ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto_transacao_fornecedor', sa.Column('quantidade', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto_transacao_fornecedor', 'quantidade')
    # ### end Alembic commands ###
